### ISSUE TITLE
Typo error in sign-up button.

### ISSUE THREAD

**Issue by azhardotcoder** [codeguyakash/safenotes#2]
![safe](https://github.com/codeguyakash/safenotes/assets/129765231/600155b0-084d-48fc-9ff1-e1bc79615667)

I noticed a bug on the sign-in page where, upon clicking the sign-in button, the sign-up button does not appear.

**Comment by codeguyakash** [comment]
Ohh, can you fix this issue ??

**Comment by azhardotcoder** [comment]
sure, I am working on it.
